#!/bin/bash

set -euo pipefail

XDG_CONFIG_HOME="$HOME/.config"

if command -v zsh >/dev/null; then
  sudo chsh -s "$(command -v zsh)" "$USER"
fi

if ! command -v chezmoi >/dev/null; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:armswk/dotfiles-devpod.git
fi

if [[ "$OSTYPE" == darwin* ]]; then
  if ! command -v brew >/dev/null; then
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  brew list pure >/dev/null 2>&1 || brew install pure
else
  if [ ! -d "$HOME/.zsh" ]; then
    mkdir -p "$HOME/.zsh"
  fi

  if [ ! -d "$HOME/.zsh/pure" ]; then
    git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
  fi
fi

if command -v alacritty >/dev/null; then
  mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
  git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME"/alacritty/themes
fi

exit 0
